[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tools.isort]
profile = "black"
src_paths = ["src/pytruankless", "tests"]
